[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

; 榨干 N16R8 的配置
; 1. 解锁 16MB 闪存空间与对应的分区表
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; 2. 解锁 8MB 八线(Octal) PSRAM
board_build.arduino.memory_type = qio_opi
build_flags = 
    -DBOARD_HAS_PSRAM
    
    ; 3. 开启 USB 虚拟串口（大部分 S3 开发板单线下载和打印必加）
    -DARDUINO_USB_CDC_ON_BOOT=1